# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site title
title: "John Choque"

# A description of your site for social meta tag, search engines, and feed.xml
description: "Finding my way to living a full life. Sharing knowledge about productivity, peace of mind and learning tools."

# The subpath of your site, e.g. /blog, for generating urls
baseurl:  ""

sass:
  sass_dir: _sass

# The base hostname & protocol of your site for where absolute urls are needed
url: "https://johnchque.com/"

# The shortname for your Disqus site to enable comments.
disqus:

# Author information - author info at the bottom of the post
author_name: "John Choque"

# Social links in the site footer
twitter_username:
facebook_username:
instagram_username:
linkedin_username: "john-choque-condori"

collections:
  projects:
    output: true
    permalink: /projects/:name

gems:
  - jekyll-paginate-v2

plugins:
  - jekyll-seo-tag

permalink: /:categories/:title:output_ext
pagination:
  enabled: true
  permalink: '/page/:num/'
  trail: 
    before: 2
    after: 2 

twitter:
  username: johnchque
  card: summary_large_image
